replicaCount: 2

image:
  repository: 474876695240.dkr.ecr.us-west-2.amazonaws.com/final-devops-django-ecr
  tag: v1.0.9
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,django,10.0.6.182,10.0.4.58,*"
  SECRET_KEY: "django-production-key-change-this"
  POSTGRES_DB: "myproject"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 512Mi

imagePullSecrets:
  - ecr-creds

nodeSelector: {}
tolerations: []
affinity: {}

podSecurityContext: {}
securityContext: {}
