controller:
  image:
    repository: jenkins/jenkins
    tag: "2.516.3"
    pullPolicy: Always

  service:
    type: LoadBalancer
    port: 8080

  # Resources
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  
  javaOpts: "-Xmx2g -Djenkins.install.runSetupWizard=false"
  serviceType: LoadBalancer
  servicePort: 8080
  
  # Plugins to install
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - pipeline-stage-view:latest
    - docker-workflow:latest
    - blueocean:latest
    - github:latest
    - aws-credentials:latest
    
  # JCasC Configuration
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Jenkins for CI/CD Pipeline"
          
        tool:
          git:
            installations:
            - name: "Default"
              home: "git"
                    
  admin:
    existingSecret: ""
    username: "admin"
    password: "your-secure-password-123"
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

# Persistence
persistence:
  enabled: true
  storageClass: "gp2"
  size: "50Gi"

# Service Account
serviceAccount:
  create: false
  name: jenkins-admin

# RBAC
rbac:
  create: true
  readSecrets: true

# Agent ВИМКНЕНИЙ
agent:
  enabled: false